// Execute the real sample-program script with a small DOM fixture, not browser QA.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('web/dashboard.html','utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
scripts.forEach(script=>new vm.Script(script));
const store=new Map();
function run(search='?view=overview&qa=1',baseline=false){
 const nodes=new Map();
 const element=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',innerHTML:'',hidden:false,value:'',listeners:{},addEventListener(k,v){this.listeners[k]=v},setAttribute(k,v){this[k]=v},showModal(){this.open=true},close(){this.open=false}});return nodes.get(id);};
 const params=new URLSearchParams(search),view=params.get('view');
 const context={params,view,sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{getElementById:element,querySelectorAll:()=>[],addEventListener(){}}};
 vm.createContext(context);vm.runInContext(scripts[1].replaceAll('{{TABLE_VARIANT}}',baseline?'baseline':'candidate'),context);
 return {context,element,submit:()=>element('program-form').listeners.submit({preventDefault(){}})};
}
let app=run();
let rows=app.element('program-rows').innerHTML;
for(const id of ['first-aid','workplace-safety','professional-development'])assert.ok(rows.includes(`program=${id}&amp;qa=1`));
assert.equal((rows.match(/<td(?: class="selection-cell")?>/g)||[]).length,56);
assert.ok(rows.includes('First aid fundamentals'));
assert.equal((rows.match(/data-action="tags"/g)||[]).length,8);
assert.equal((rows.match(/data-action="edit"/g)||[]).length,8);
assert.equal((rows.match(/data-action="delete"/g)||[]).length,8);
vm.runInContext("openProgramAction('workplace-safety','edit')",app.context);
assert.equal(app.element('program-dialog').open,true);
app.element('program-name').value='Safety & compliance <course>';
app.element('template-name').value='Safety award';app.element('course-name').value='first-aid-course';app.submit();
assert.equal(app.element('program-dialog').open,false);
assert.ok(app.element('program-rows').innerHTML.includes('Safety &amp; compliance &lt;course&gt;'));
app=run('?view=program&program=workplace-safety');
assert.equal(app.element('program-title').textContent,'Safety & compliance <course>');
assert.equal(app.element('program-template').textContent,'Certificate template: Safety award');
assert.ok(app.element('program-course').textContent.includes('First aid fundamentals'));
assert.ok(app.element('program-course').textContent.includes('before a certificate is issued'));
vm.runInContext("openProgramAction('workplace-safety','delete')",app.context);
app.element('cancel-program').listeners.click();
assert.equal(vm.runInContext('programs.length',app.context),8);
vm.runInContext("openProgramAction('workplace-safety','delete')",app.context);app.submit();
assert.equal(vm.runInContext('programs.length',app.context),7);
assert.equal(app.element('program-title').textContent,'Program unavailable');
assert.equal(app.element('total-renewals').textContent,57);
assert.equal(app.element('total-issued').textContent,'1,384');
app=run();assert.equal(vm.runInContext('programs.length',app.context),7);
app.element('reset-programs').listeners.click();
assert.equal(vm.runInContext('programs.length',app.context),8);
assert.equal(app.element('total-issued').textContent,'1,775');
assert.equal(app.element('program-count').textContent,8);
console.log('PASS: all program links, QA marker, edit/save, safe text, navigation, delete cancellation/confirmation, totals, session persistence and reset.');

// Tags show two initially; expand/collapse and modal edits are real script behavior.
assert.ok(app.element('program-rows').innerHTML.includes('+1 more'));
assert.ok(!app.element('program-rows').innerHTML.split('</tr>')[0].includes('>Compliance</span>'));
vm.runInContext("openProgramAction('first-aid','toggle-tags')",app.context);
assert.ok(app.element('program-rows').innerHTML.split('</tr>')[0].includes('>Compliance</span>'));
assert.ok(app.element('program-rows').innerHTML.includes('aria-expanded="true"'));
vm.runInContext("openProgramAction('first-aid','toggle-tags')",app.context);
assert.ok(!app.element('program-rows').innerHTML.split('</tr>')[0].includes('>Compliance</span>'));
vm.runInContext("openProgramAction('first-aid','tags')",app.context);
assert.equal(app.element('tags-dialog').open,true);
app.element('new-tag').value='healthcare';app.element('add-tag').listeners.click();
assert.equal(vm.runInContext('draftTags.length',app.context),3);
assert.ok(app.element('tag-error').textContent.includes('already added'));
for(const name of ['First responder','External training']){app.element('new-tag').value=name;app.element('add-tag').listeners.click();}
assert.equal(vm.runInContext('draftTags.length',app.context),5);
assert.equal(app.element('add-tag').disabled,true);
app.element('new-tag').value='Sixth tag';app.element('add-tag').listeners.click();
assert.equal(vm.runInContext('draftTags.length',app.context),5);
assert.ok(app.element('tag-error').textContent.includes('up to 5'));
app.element('tag-list').listeners.click({target:{closest:()=>({dataset:{removeTag:'0'}})}});
assert.equal(vm.runInContext('draftTags.length',app.context),4);
assert.equal(app.element('add-tag').disabled,false);
app.element('new-tag').value='<script>bad</script>';
let prevented=false;app.element('new-tag').listeners.keydown({key:'Enter',preventDefault(){prevented=true}});assert.ok(prevented);
assert.ok(app.element('tag-list').innerHTML.includes('&lt;script&gt;bad&lt;/script&gt;'));
app.element('tags-form').listeners.submit({preventDefault(){}});
assert.equal(app.element('tags-dialog').open,false);
assert.equal(vm.runInContext("programs.find(p=>p.id==='first-aid').tags.length",app.context),5);
app=run();assert.equal(vm.runInContext("programs[0].tags.length",app.context),5);
vm.runInContext("openProgramAction('first-aid','tags')",app.context);
app.element('tag-list').listeners.click({target:{closest:()=>({dataset:{removeTag:'0'}})}});
app.element('cancel-tags').listeners.click();
assert.equal(vm.runInContext('programs[0].tags.length',app.context),5);
vm.runInContext("openProgramAction('first-aid','tags')",app.context);assert.equal(vm.runInContext('draftTags.length',app.context),5);
// Baseline keeps Program, Course, Actions only; baseline edits preserve candidate tags/templates.
app=run('?view=overview&qa=1',true);rows=app.element('program-rows').innerHTML;
assert.equal((rows.match(/<td>/g)||[]).length,24);assert.ok(!rows.includes('Manage tags'));assert.ok(!rows.includes('class="status"'));
vm.runInContext("openProgramAction('first-aid','tags')",app.context);assert.equal(app.element('tags-dialog').open,undefined);
vm.runInContext("openProgramAction('first-aid','edit')",app.context);assert.equal(app.element('template-field').hidden,true);
app.element('template-name').value='';app.element('course-name').value='safety-course';app.submit();
app=run();assert.equal(vm.runInContext('programs[0].template',app.context),'First aid certificate');assert.equal(vm.runInContext('programs[0].courseId',app.context),'safety-course');assert.equal(vm.runInContext('programs[0].tags.length',app.context),5);
// Old saved rows receive course/tag defaults without restoring deleted rows.
store.delete('certification-demo-programs-v2');store.set('certification-demo-programs-v1',JSON.stringify([{id:'first-aid',name:'Existing edit',template:'Existing template',issued:482,renewals:18}]));app=run();
assert.equal(vm.runInContext('programs.length',app.context),6);assert.equal(vm.runInContext('programs[0].name',app.context),'Existing edit');assert.equal(vm.runInContext('programs[0].courseId',app.context),'first-aid-course');assert.equal(vm.runInContext('programs[0].tags.length',app.context),3);
console.log('PASS: associated-course edits, baseline/candidate columns, five-tag cap, duplicate rejection, add/remove, expand/collapse, safe rendering, save/cancel, persistence and old-data migration.');

// Exercise selection and bulk mutation, including atomic validation and cancellation.
store.clear();app=run();
assert.equal((app.element('program-rows').innerHTML.match(/data-select-program=/g)||[]).length,8);
assert.equal(app.element('bulk-actions').hidden,true);
const select=(id,checked)=>app.element('program-rows').listeners.change({target:{closest:()=>({dataset:{selectProgram:id},checked})}});
select('first-aid',true);assert.equal(app.element('select-all').indeterminate,true);assert.equal(app.element('bulk-actions').hidden,true);
select('workplace-safety',true);assert.equal(app.element('bulk-actions').hidden,false);assert.equal(app.element('selection-count').textContent,'2 selected');
app.element('select-all').listeners.change({target:{checked:true}});assert.equal(app.element('selection-count').textContent,'8 selected');assert.equal(app.element('select-all').checked,true);assert.equal(app.element('toggle-select-all').textContent,'Deselect all');
app.element('toggle-select-all').listeners.click();assert.equal(app.element('selection-count').textContent,'0 selected');
select('first-aid',true);select('workplace-safety',true);
const add=name=>{app.element('new-tag').value=name;app.element('add-tag').listeners.click()};
const saveTags=()=>app.element('tags-form').listeners.submit({preventDefault(){}});
app.element('bulk-tags').listeners.click();for(const t of ['One','Two','Three'])add(t);
const before=vm.runInContext('JSON.stringify(programs)',app.context);saveTags();assert.equal(vm.runInContext('JSON.stringify(programs)',app.context),before);assert.ok(app.element('tag-error').textContent.includes('exceed 5'));assert.equal(app.element('tags-dialog').open,true);
app.element('cancel-tags').listeners.click();assert.equal(vm.runInContext('JSON.stringify(programs)',app.context),before);
app.element('bulk-tags').listeners.click();add('Compliance');add('Shared');saveTags();
assert.equal(vm.runInContext('programs[0].tags.length',app.context),4);assert.equal(vm.runInContext('programs[1].tags.length',app.context),4);assert.equal(app.element('tags-dialog').open,false);
app.element('bulk-tags').listeners.click();app.element('bulk-tag-mode').value='remove';add('COMPLIANCE');saveTags();
assert.equal(vm.runInContext('programs[0].tags.length',app.context),3);assert.equal(vm.runInContext('programs[1].tags.length',app.context),3);
app.element('bulk-delete').listeners.click();app.element('cancel-program').listeners.click();assert.equal(vm.runInContext('programs.length',app.context),8);
app.element('bulk-delete').listeners.click();app.submit();assert.equal(vm.runInContext('programs.length',app.context),6);assert.equal(app.element('selection-count').textContent,'0 selected');assert.equal(app.element('bulk-actions').hidden,true);
app=run();assert.equal(vm.runInContext('programs.length',app.context),6);app.element('reset-programs').listeners.click();assert.equal(vm.runInContext('programs.length',app.context),8);
app=run('?view=overview',true);assert.equal(app.element('selection-tools').hidden,true);assert.ok(!app.element('program-rows').innerHTML.includes('data-select-program'));
console.log('PASS: eight rows, individual/select-all/deselect-all, bulk tag add/remove, atomic five-tag validation, cancellation, bulk deletion, persistence and candidate-only selection.');
